object AppDependencies {
  const val kotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin_version}"
  const val kotlinCore = "androidx.core:core-ktx:${Versions.kotlin_core}"
  const val appCompat = "androidx.appcompat:appcompat:${Versions.app_compat_version}"
  const val material = "com.google.android.material:material:${Versions.material_version}"
  const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraint_layout_version}"
  const val androidFragment = "androidx.fragment:fragment-ktx:${Versions.fragment_version}"
  const val junit = "junit:junit:${Versions.junit_version}"
  const val extJunit = "androidx.test.ext:junit:${Versions.ext_junit_version}"
  const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espresso_version}"
  const val navigationFragment = "androidx.navigation:navigation-fragment-ktx:${Versions.navigation_fragment_version}"
  const val navigationAndroid = "androidx.navigation:navigation-ui-ktx:${Versions.navigation_android_version}"
  const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines_version}"
  const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.livecycleViewModel_version}"
  const val lifecycleLiveData = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.livecycleLiveData_version}"
  const val room = "androidx.room:room-runtime:${Versions.room_version}"
  const val roomCompiler = "androidx.room:room-compiler:${Versions.roomCompiler_version}"
  const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit_version}"
  const val moshiConverter = "com.squareup.retrofit2:converter-moshi:${Versions.moshi_version}"
  const val securityCrypto = "androidx.security:security-crypto:${Versions.security_crypto_version}"
}
